RPM spec: fix comments
For whatever reason, the builds now fail because it thinks # is a character
being used for versions instead of a comment.  Not sure this is happening
now when the spec file hasn't changed; presumably some tooling version is
different.

> error: line 122: Dependency tokens must begin with alpha-numeric,
  '_' or '/': Requires: gnutls # To enumerate system certificates

Signed-off-by: Mark Yen <mark.yen@suse.com>