BATS: profile: Pass Windows paths to reg.exe for export
We appear to be failing tests when exporting the profile to disk:

ERROR: Unable to write to the file. There may be a disk or file system
error.

On the assumption that this is due to Linux paths being passed to a Windows
application, try it with Windows paths.

Signed-off-by: Mark Yen <mark.yen@suse.com>