Use `127.0.0.1` instead of `localhost`
This resolves an error we were experiencing in the test

```
FetchError: request to http://localhost:6109/list failed, reason: connect ECONNREFUSED ::1:6109
```

Node.js used to favor IPv4 but that changed in v17

> It's #39987 -- Node.js now returns IP addresses in the order they are returned from the name resolver/DNS. There's a --dns-result-order command line option you can set to control the behaviour -- the difference in Node.js 17 is the default changed.

https://github.com/nodejs/node/issues/40537#issuecomment-948047193

Signed-off-by: Phillip Rak <rak.phillip@gmail.com>